apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/virtualservice.yaml
- ../../base/destinationrule.yaml

namePrefix: dev-

labels:
- pairs:
    environment: dev

images:
- name: ghcr.io/jbluemel/user-service-demo
  newTag: main-d0f5210a545512c89597cd2f442277f5aeb3b15a
