apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/virtualservice.yaml
- ../../base/destinationrule.yaml

namePrefix: dev-

labels:
- pairs:
    environment: dev
  